services:
  php-apache:
    container_name: php-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: framework_php
    networks:
      - app-network
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
networks:
  app-network:
    driver: bridge